### ISSUE TITLE
Rotation isn't working as expected

### ISSUE THREAD

**Issue by ghost** [l-jdavies/pacman#1]
Hi, hope you are well!

I was trying to play the game, but my pacman doesn't rotate well, I place it facing SOUTH, rotate LEFT, then RIGHT and end up facing NORTH, Is it a bug?
Steps to reproduce:
```
PLACE,1,2,SOUTH
LEFT
RIGHT
REPORT
```

Result:
```
Position report:
X: 1
Y: 2
F: NORTH
```

Expected result:
```
Position report:
X: 1
Y: 2
F: SOUTH
```

Would you be able to assist with investigation/fix?

**Comment by l-jdavies** [comment]
Hi Alexandr,

Apologies for that. There was a bug when a user enters the "RIGHT" command, the `handleLeft` function was being invoked by mistake. The fix can be found [here](https://github.com/l-jdavies/pacman/commit/2ff3d2a2279d7878ac874de08b699b87ad53a8c6) and has been pushed to `main`.

**Comment by ghost** [comment]
Hi Laura,

No worries at all, thanks for the quick fix!
I'll pull the change shortly
